FROM golang:latest

RUN apt-get update && \
    apt-get install -y libsnmp-dev p7zip-full

COPY ./generator  /bin/generator

WORKDIR "/opt"
RUN ll /usr/lib/x86_64-linux-gnu/libnetsnmp*
ENTRYPOINT ["/bin/generator"]

ENV MIBDIRS mibs

CMD ["generate"]
